// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using freightWebApp.Data;

namespace freightWebApp.Migrations
{
    [DbContext(typeof(freightWebAppContext))]
    [Migration("20200714203007_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("freightWebApp.Models.Freight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Commodity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Linehaul")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Freight");
                });
#pragma warning restore 612, 618
        }
    }
}
